// Generated by CoffeeScript 1.3.3
(function() {
  var ELEMENT_NODE, SocialString, TEXT_NODE, walk,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TEXT_NODE = 3;

  ELEMENT_NODE = 1;

  walk = function(el) {
    var kid, kids;
    if (el.nodeType === TEXT_NODE) {
      return "Text: " + el.nodeValue;
    } else if (el.nodeType === ELEMENT_NODE) {
      if (el.hasChildNodes) {
        return kids = (function() {
          var _i, _len, _ref, _results;
          _ref = el.childNodes;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            kid = _ref[_i];
            _results.push(walk(kid));
          }
          return _results;
        })();
      }
    }
  };

  SocialString = (function(_super) {

    __extends(SocialString, _super);

    function SocialString(string) {
      this.string = string;
      ({
        shrink: function() {
          return "Shrink: " + this;
        }
      });
    }

    return SocialString;

  })(String);

  walk(document.head);

}).call(this);
